version: '2.3'

services:

  ## 80: Reverse proxy.
  traefik:
    image: traefik
    container_name: "${PROJECT_ID}_traefik"
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '${PROJECT_PORT}:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:cached
    networks:
      default:
        aliases:
          - "${PROJECT_ID}.localhost"
          - "api.${PROJECT_ID}.localhost"
          - "www.${PROJECT_ID}.localhost"

  ## 3000: Node.
  node:
    build:
      context: ./www
      dockerfile: Dockerfile
    image: "${PROJECT_ID}-frontend"
    command: [ "npm", "run", "dev" ]
    ports:
      - "3000:3000"
    env_file:
      - .env
    labels:
      - 'traefik.backend=frontend'
      - 'traefik.port=3000'
      - 'traefik.frontend.passHostHeader=true'
      - 'traefik.frontend.rule=Host:${PROJECT_ID}.localhost,www.${PROJECT_ID}.localhost'
    volumes:
      - ./www:/app:cached

  ## 3306: Database.
  database:
    build: ./api/docker/database
    container_name: "${PROJECT_ID}_database"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    env_file:
      - .env
    volumes:
      - ./database:/var/lib/mysql

  ## 8080: Nginx.
  nginx:
    build:
      context: ./api
      dockerfile: docker/nginx/Dockerfile
      args:
        CLI_IMAGE: "${PROJECT_ID}-backend"
    ports:
      - "8080:80"
    env_file:
      - .env
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=8080'
      - 'traefik.frontend.passHostHeader=true'
      - 'traefik.frontend.rule=Host:api.${PROJECT_ID}.localhost'
    volumes:
      - ./api:/app:cached
    depends_on:
      - cli

  ## 9000: CLI.
  cli:
    build:
      context: ./api
      dockerfile: docker/cli/Dockerfile
    image: "${PROJECT_ID}-backend"
    env_file:
      - .env
    volumes:
      - ./api:/app:cached

  ## 9000: PHP.
  php:
    build:
      context: ./api
      dockerfile: docker/php/Dockerfile
      args:
        CLI_IMAGE: "${PROJECT_ID}-backend"
    env_file:
      - .env
    volumes:
      - ./api:/app:cached
    depends_on:
      - cli